### ISSUE TITLE
Strings with ampersands are cut off

### ISSUE THREAD

**Issue by jonathanbell** [sdkcodes/heroku-config#1]
Not really a huge deal. I more wanted to say thank you! You saved me a lot time! 👍 

Strings like `PW=djfkslkds&123` come across to Heroku like `djfkslkds` (probably because Python or Bash see `&` as a reserved character. 

Again -- thanks so much!

**Comment by sdkcodes** [comment]
Good to hear from you, I'll look into that to see if I can fix it.
But if you think you have a fix, please do and send a PR

**Comment by jonathanbell** [comment]
No movement on this - closing/tidying up
